create table "public"."product_reviews" (
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "product_id" bigint not null,
    "id" bigint generated by default as identity not null,
    "content" text not null
);


alter table "public"."product_reviews" enable row level security;

create table "public"."products" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "price" bigint not null
);


alter table "public"."products" enable row level security;

create table "public"."users" (
    "user_id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX product_reviews_id_key ON public.product_reviews USING btree (id);

CREATE UNIQUE INDEX product_reviews_pkey ON public.product_reviews USING btree (id);

CREATE UNIQUE INDEX products_pkey ON public.products USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (user_id);

alter table "public"."product_reviews" add constraint "product_reviews_pkey" PRIMARY KEY using index "product_reviews_pkey";

alter table "public"."products" add constraint "products_pkey" PRIMARY KEY using index "products_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."product_reviews" add constraint "product_reviews_content_check" CHECK ((length(content) > 0)) not valid;

alter table "public"."product_reviews" validate constraint "product_reviews_content_check";

alter table "public"."product_reviews" add constraint "product_reviews_id_key" UNIQUE using index "product_reviews_id_key";

alter table "public"."product_reviews" add constraint "product_reviews_product_id_fkey" FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE not valid;

alter table "public"."product_reviews" validate constraint "product_reviews_product_id_fkey";

alter table "public"."product_reviews" add constraint "product_reviews_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL not valid;

alter table "public"."product_reviews" validate constraint "product_reviews_user_id_fkey";

grant delete on table "public"."product_reviews" to "anon";

grant insert on table "public"."product_reviews" to "anon";

grant references on table "public"."product_reviews" to "anon";

grant select on table "public"."product_reviews" to "anon";

grant trigger on table "public"."product_reviews" to "anon";

grant truncate on table "public"."product_reviews" to "anon";

grant update on table "public"."product_reviews" to "anon";

grant delete on table "public"."product_reviews" to "authenticated";

grant insert on table "public"."product_reviews" to "authenticated";

grant references on table "public"."product_reviews" to "authenticated";

grant select on table "public"."product_reviews" to "authenticated";

grant trigger on table "public"."product_reviews" to "authenticated";

grant truncate on table "public"."product_reviews" to "authenticated";

grant update on table "public"."product_reviews" to "authenticated";

grant delete on table "public"."product_reviews" to "service_role";

grant insert on table "public"."product_reviews" to "service_role";

grant references on table "public"."product_reviews" to "service_role";

grant select on table "public"."product_reviews" to "service_role";

grant trigger on table "public"."product_reviews" to "service_role";

grant truncate on table "public"."product_reviews" to "service_role";

grant update on table "public"."product_reviews" to "service_role";

grant delete on table "public"."products" to "anon";

grant insert on table "public"."products" to "anon";

grant references on table "public"."products" to "anon";

grant select on table "public"."products" to "anon";

grant trigger on table "public"."products" to "anon";

grant truncate on table "public"."products" to "anon";

grant update on table "public"."products" to "anon";

grant delete on table "public"."products" to "authenticated";

grant insert on table "public"."products" to "authenticated";

grant references on table "public"."products" to "authenticated";

grant select on table "public"."products" to "authenticated";

grant trigger on table "public"."products" to "authenticated";

grant truncate on table "public"."products" to "authenticated";

grant update on table "public"."products" to "authenticated";

grant delete on table "public"."products" to "service_role";

grant insert on table "public"."products" to "service_role";

grant references on table "public"."products" to "service_role";

grant select on table "public"."products" to "service_role";

grant trigger on table "public"."products" to "service_role";

grant truncate on table "public"."products" to "service_role";

grant update on table "public"."products" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


